// Metadata for the public pages.
//
// This is not housekeeping — it is the word-of-mouth surface. The distribution
// strategy is a coach pasting a link to a programme manager on WhatsApp
// (docs/web-and-support-2026-09.md §5), and a link with no Open Graph tags
// renders as a bare grey URL. The preview card IS the first impression, and it
// is seen by more people than the page itself: everyone in the group chat sees
// the card, only some of them tap it.
//
// So every public page gets a real title, a real description, and the shared
// image generated by src/app/opengraph-image.tsx.

import type { Metadata } from 'next'

// Vercel sets VERCEL_URL for every deployment including previews, so the
// fallback works without configuration — but a preview URL in a shared card is
// wrong, which is why NEXT_PUBLIC_SITE_URL should be set to the real domain in
// production. No domain is hardcoded here because guessing one would silently
// point every card at a host we do not control.
export const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000')

export const SITE_NAME = 'Shared Sailing Analytics'

/**
 * Build a page's metadata with the social card filled in.
 *
 * Next does not reliably derive `openGraph.title`/`description` from the plain
 * `title`/`description` fields, so they are set explicitly rather than hoped
 * for — a silently empty card is exactly the failure this file exists to stop.
 */
export function pageMeta({
  title,
  description,
  path,
}: {
  title: string
  description: string
  path: string
}): Metadata {
  const url = new URL(path, siteUrl).toString()
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      type: 'website',
      locale: 'en_GB',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
  }
}
