// Metadata for the public pages.
//
// This is not housekeeping — it is the word-of-mouth surface. The distribution
// strategy is a coach pasting a link to a programme manager on WhatsApp
// (docs/web-and-support-2026-09.md §5), and a link with no Open Graph tags
// renders as a bare grey URL. The preview card IS the first impression, and it
// is seen by more people than the page itself: everyone in the group chat sees
// the card, only some of them tap it.
//
// So every public page gets a real title, a real description, and the shared
// image generated by src/app/opengraph-image.tsx.

import type { Metadata } from 'next'

// The canonical host, and it is deliberately NOT VERCEL_URL.
//
// Canonical links, sitemap entries and social cards must all name the one host
// the site actually lives at. VERCEL_URL is a different value on every
// deployment, so using it would mean a preview build advertising itself as the
// site: cards pointing at a URL that will 404 next week, and a sitemap offering
// crawlers a hostname that is not the product. Previews wanting their own value
// set NEXT_PUBLIC_SITE_URL explicitly.
const PRODUCTION_URL = 'https://ssa.wvsailing.co.uk'

export const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || PRODUCTION_URL

export const SITE_NAME = 'Shared Sailing Analytics'

/**
 * Build a page's metadata with the social card filled in.
 *
 * Next does not reliably derive `openGraph.title`/`description` from the plain
 * `title`/`description` fields, so they are set explicitly rather than hoped
 * for — a silently empty card is exactly the failure this file exists to stop.
 */
export function pageMeta({
  title,
  description,
  path,
}: {
  title: string
  description: string
  path: string
}): Metadata {
  const url = new URL(path, siteUrl).toString()
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      type: 'website',
      locale: 'en_GB',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
    },
  }
}
